[build]
  builder = "NIXPACKS"
  buildCommand = ""

[deploy]
  startCommand = "gunicorn app:app"
  healthcheckPath = "/healthz"
  healthcheckTimeout = 100
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[[services]]
  autoDeploy = true